### PR TITLE
Link check

### PR DESCRIPTION
**Pull request by starwed**
This adds a grunt script for checking for dead links... and also fixes various broken links I found by running it.

This isn't really ready to land yet, because I need to add a commit that actually generates the site -- and that means merging my other PR first.

### CODE REVIEW

**Comment by starwed** [comment]
I merged this -- there are actually still quite a few broken links in the api, but this is because of some incorrect linking in the source docs.

**Comment by kevinsimper** [comment]
Looks good! :) Very nice with something automatic!

But we should possible get away from github pages, because every commit is getting massive when you have to commit the changes as well :/

**Comment by starwed** [comment]
>But we should possible get away from github pages, because every commit is getting massive when you have to commit the changes as well :/

Yeah, this has been bugging me.  Two similar solutions, without moving off of gh-pages:

- Move the site generation code into a separate repo
- Use a different branch for the generation code as if it were a separate repo

In either case, I think we could configure Travis to build and update the actual site.

**Comment by kevinsimper** [comment]
I think we should create a new repository called "Crafty.js website" that have the website on `master` and then it deploys to this repository.

I think what talks against doing another branch on this repository is that there will be automatic git commits and it will be inbetween commits and we can disable issues and pull requests to this repository and thereby avoid people commeting and sending pull request to the wrong branch.

**Comment by kevinsimper** [comment]
@starwed What do you think of create a new repository that contains the website, that then deploys to this repository?

**Comment by starwed** [comment]
That sounds pretty reasonable to me.  

The other option I've thought about would be to put it in a directory of the main Crafty repo.  That would solve the problem of duplicated code, but make it harder to automate updating the site.  So I'm leaning towards the completely separate repo idea.

What would we call it, "crafty-site-source" maybe?

**Comment by kevinsimper** [comment]
I would prefer something simple like "crafty-website" and then just write it in the readme here, but you decide, you're the only one who can create new repos? :)

**Comment by starwed** [comment]
Sure, `crafty-website` is fine.  I'll try to set that up in the next day or two.  (There's a bit of work that needs to be done on the build scripts to allow it.)

**Comment by kevinsimper** [comment]
I see that you created it! Great :)

**Pull request merged**
